force-app/main/default/objects/NEO_Rule__c/NEO_Rule__c.object-meta.xml
<CustomObject>
    <description>For rule engine</description>
    <label>NEO Rule</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>NEO Rules Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NEO_Rule__c/fields/Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>Alert_Message__c</fullName>
    <label>Alert Message(CN)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NEO_Rule__c/fields/Hard_Stop_Warning__c.field-meta.xml
<CustomField>
    <fullName>Hard_Stop_Warning__c</fullName>
    <label>Hard Stop/Warning</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hard Stop</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NEO_Rule__c/fields/NEO_Alert_Message_EN__c.field-meta.xml
<CustomField>
    <fullName>NEO_Alert_Message_EN__c</fullName>
    <label>Alert Message(EN)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NEO_Rules_Handler.cls
public virtual class NEO_Rules_Handler implements NEO_Rules_Constants.RuleHandler {

    public void handleRealtime(List<SObject> objList, String objectType, String triggerType) {
        /*
        if (NEO_Constants.NEO_IS_INTEGRATION_USER) {
            return;
        }*/
        
    	Map<String,List<NEO_Rule__c>> realTimeTriggeredRulesList = NEO_Rules_Utils.rulesRealtimeCheck(objList, objectType, triggerType);
        
        // zh_CN / en_US
        String strUserLanguage = UserInfo.getLanguage();

    	String tempKey = '';
    	Integer rowIndex = 0;

    	for (SOBject sobjectRow : objList) {
    		Object tempObjectId = sobjectRow.get('Id');
    		if (tempObjectId == null) {
				tempKey = String.valueOf(rowIndex);
    		} else {
    			tempKey = String.valueOf(tempObjectId);
    		}
    		++rowIndex;

    		if (!realTimeTriggeredRulesList.containsKey(tempKey)) {
    			continue;
    		}

            Set<String> hardStopMsgSet = new Set<String>();
			for (NEO_Rule__c tempRuleRow : realTimeTriggeredRulesList.get(tempKey)) {
				if (tempRuleRow.Hard_Stop_Warning__c == NEO_Rules_Constants.NEO_STRING_HARD_STOP) {
                    String strAlertMessage = tempRuleRow.Alert_Message__c;
                    String strAlertMessageEN = tempRuleRow.NEO_Alert_Message_EN__c;
                    if (strUserLanguage == 'en_US' && String.isNotBlank(strAlertMessageEN)) {
                        strAlertMessage = strAlertMessageEN;
                    }

					// Stop
                    hardStopMsgSet.add(strAlertMessage);
				}
			}

			if (hardStopMsgSet.size() > 0) {
				sobjectRow.addError(String.join(new List<String>(hardStopMsgSet), '<br />'), false);
			}
    	}
    }
}